# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.



In [2]:
import numpy as np
array = np.random.randint(1,21, size=(5,5))
print(array)

array[:, 2] = 1
print(array)

[[ 8  9  8  4  4]
 [17  4  9  1  9]
 [ 2  5  8  1  6]
 [ 4 13 10 20 16]
 [ 1 10  4  4  4]]
[[ 8  9  1  4  4]
 [17  4  1  1  9]
 [ 2  5  1  1  6]
 [ 4 13  1 20 16]
 [ 1 10  1  4  4]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.



In [3]:
array = np.random.randint(1,17, size=(4,4))
print(array)

np.fill_diagonal(array,0)
print(array)

[[ 5 14 12 12]
 [12 13 14  1]
 [ 9 13  1  8]
 [ 9 13  5 13]]
[[ 0 14 12 12]
 [12  0 14  1]
 [ 9 13  0  8]
 [ 9 13  5  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.


In [4]:
# array = np.random.randint(1,37, size=[6,6])
# print(array)
array = np.arange(1,37).reshape((6,6))
print(array)

sub_array = array[2:5, 1:4]
print(sub_array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.



In [5]:
array = np.random.randint(1, 100, size=[5,5])
print(array)

border_elements = np.concatenate((array[0, :], array[-1,:], array[1:-1,0], array[1:-1,-1]))
print(border_elements)

[[92 29 22 85 63]
 [60 33 27 28 78]
 [71 60 47 72 69]
 [75 75 27 88 24]
 [51 78 24 14 10]]
[92 29 22 85 63 51 78 24 14 10 60 71 75 78 69 24]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.


In [6]:
array1 = np.random.randint(1,99, size=(3,4))
print(array1)
array2 = np.random.randint(1,99, size=(3,4))
print(array2)
add = array1 + array2
print(add)
sub = array1 - array2
print(sub)
mult = array1 * array2
print(mult)
div = array1 / array2
print(div)


[[73 39 65 23]
 [63 27 42 25]
 [44 20 63 91]]
[[61 78 49 64]
 [ 9 61 24 15]
 [ 3 88 45 33]]
[[134 117 114  87]
 [ 72  88  66  40]
 [ 47 108 108 124]]
[[ 12 -39  16 -41]
 [ 54 -34  18  10]
 [ 41 -68  18  58]]
[[4453 3042 3185 1472]
 [ 567 1647 1008  375]
 [ 132 1760 2835 3003]]
[[ 1.19672131  0.5         1.32653061  0.359375  ]
 [ 7.          0.44262295  1.75        1.66666667]
 [14.66666667  0.22727273  1.4         2.75757576]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.



In [7]:
array = np.random.randint(1,17, size=(4,4))
print(array)
row_sum = np.sum(array, axis=1)
print(row_sum)
column_sum = np.sum(array, axis=0)
print(column_sum)


[[16  4  2  8]
 [15  1 10 15]
 [15 10 10  1]
 [10 11 14  5]]
[30 41 36 40]
[56 26 36 29]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.


In [8]:
array = np.random.randint(1,99, size=(5,5))
print(array)
mean = np.mean(array)
print(mean)
median= np.median(array)
print(median)
std = np.std(array)
print(std)
variance = np.var(array)
print(variance)

[[43 70 70 27 93]
 [58 78 49 45 42]
 [60  4 80 96 11]
 [64 13 95 29 45]
 [95 49 21 93 53]]
55.32
53.0
27.56188672787115
759.6576


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).


In [9]:
array = np.random.randint(1,10, size= (3,3))
print(array)
mean = np.mean(array)
std = np.std(array)
print(mean)
print(std)
normalize = (array-mean)/std
print(normalize)

[[7 3 5]
 [7 9 1]
 [2 8 9]]
5.666666666666667
2.8674417556808756
[[ 0.46499055 -0.92998111 -0.23249528]
 [ 0.46499055  1.16247639 -1.62746694]
 [-1.27872403  0.81373347  1.16247639]]



### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [14]:
array = np.random.randint(1,10, size=(3,3))
print(array)
dete = np.linalg.det(array)
print(dete)
inverse = np.linalg.inv(array)
print(inverse)
eigen_value = np.linalg.eigvals(array)
print(eigen_value)

[[2 9 4]
 [2 6 1]
 [7 4 7]]
-123.00000000000006
[[-0.30894309  0.38211382  0.12195122]
 [ 0.05691057  0.11382114 -0.04878049]
 [ 0.27642276 -0.44715447  0.04878049]]
[12.8555733  -2.20154231  4.34596902]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.



In [17]:
ary = np.random.randint(1,10,size=(4,4))
print(ary)
ary_one = np.random.randint(1,10,size=(4,))
print(ary_one)
result = ary + ary_one
print(result)

[[9 7 4 6]
 [2 7 3 2]
 [5 9 7 2]
 [4 2 9 4]]
[4 8 9 6]
[[13 15 13 12]
 [ 6 15 12  8]
 [ 9 17 16  8]
 [ 8 10 18 10]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.



### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).



### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.



### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.



### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.